export const REGISTER_USER = 'REGISTER_USER'
export const LOGIN_USER = 'LOGIN_USER'
export const LOAD_USER = 'LOAD_USER'
export const CLEAR_USER = 'CLEAR_USER'
export const SAVE_LAST_USER = 'SAVE_LAST_USER'
export const CLEAR_LAST_USER = 'CLEAR_LAST_USER'
export const ADD_ACCOUNT = 'ADD_ACCOUNT'
export const REMOVE_ACCOUNT = 'REMOVE_ACCOUNT'
