export const LOAD_USER = 'LOAD_USER'
export const ERROR_USER = 'ERROR_USER'
export const CLEAR_USER = 'CLEAR_USER'
export const CLEAR_ERROR = 'CLEAR_ERROR'
export const ADD_ACCOUNT = 'ADD_ACCOUNT'
export const REMOVE_ACCOUNT = 'REMOVE_ACCOUNT'
